# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0992b767c6965ce15f48fc3452b4da448b82ece24b8345d2ef9ff40e5af28e3463a1df1a076a4e92eff511266609904b4182ec0285e1cdde2fbf1b341c7989d1

test:
  secret_key_base: fe0c9c65396507f60ae73baba2aaf64df43ab7063c9c4854596d2880f5951f0d20eae7f260c7a1fefe50d488437fb57ab330fbbdb9c2118a8bb76ce0f63bff90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
